git initversion: "3.9"
services:
  postgres:
    build:
      context: ./docker
      dockerfile: pgsql/Dockerfile
    container_name: $APP_NAME-postgres
    working_dir: /var/www
    environment:
      POSTGRES_DB: $DATABASE_NAME
      POSTGRES_USER: $DATABASE_USER
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - .:/var/www
      - ./data/postgres:/var/lib/postgresql/data:rw
    ports:
      - $DATABASE_PORT:5432
    networks:
      - efin

  webserver:
    image: nginx:alpine
    container_name: $APP_NAME-webserver
    volumes:
      - ../../source:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - $WEBSERVER_PORT:80
    environment:
      XDEBUG_CONFIG: "remote_host=host.docker.internal remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"
    networks:
      - efin
    depends_on:
      - php-fpm
      - fpm-cli

  php-fpm:
    build:
      context: ./docker
      dockerfile: php-fpm/Dockerfile
    container_name: $APP_NAME-fpm
    volumes:
      - ../../source:/var/www
      - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini
      - ./docker/php-fpm/xdebug.ini:/etc/php/8.1/fpm/conf.d/xdebug.ini
    environment:
      PHP_IDE_CONFIG: "serverName=xdebugserver"
    networks:
      - efin
    depends_on:
      - postgres

  fpm-cli:
    build:
      context: ./docker
      dockerfile: php-fpm/cli/Dockerfile
    container_name: $APP_NAME-fpm-cli
    volumes:
      - ../../source:/var/www
      - ./docker/php-fpm/cli/php-ini-overrides.ini:/etc/php/8.1/cli/conf.d/99-overrides.ini
      - ./docker/php-fpm/cli/xdebug.ini:/etc/php/8.1/cli/conf.d/xdebug.ini
    networks:
      - efin
    depends_on:
      - postgres

networks:
  efin:
    driver: bridge